#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xwd
Version  : 1.0.8
Release  : 8
URL      : https://www.x.org/releases/individual/app/xwd-1.0.8.tar.gz
Source0  : https://www.x.org/releases/individual/app/xwd-1.0.8.tar.gz
Source1  : https://www.x.org/releases/individual/app/xwd-1.0.8.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xwd-bin = %{version}-%{release}
Requires: xwd-license = %{version}-%{release}
Requires: xwd-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xkbfile)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
xwd - dump an image of an X window
----------------------------------
All questions regarding this software should be directed at the
Xorg mailing list:

%package bin
Summary: bin components for the xwd package.
Group: Binaries
Requires: xwd-license = %{version}-%{release}

%description bin
bin components for the xwd package.


%package license
Summary: license components for the xwd package.
Group: Default

%description license
license components for the xwd package.


%package man
Summary: man components for the xwd package.
Group: Default

%description man
man components for the xwd package.


%prep
%setup -q -n xwd-1.0.8
cd %{_builddir}/xwd-1.0.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1627928608
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1627928608
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xwd
cp %{_builddir}/xwd-1.0.8/COPYING %{buildroot}/usr/share/package-licenses/xwd/6b0e3fce4ba4e2a4fba4301ed4e356885de100f7
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xwd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xwd/6b0e3fce4ba4e2a4fba4301ed4e356885de100f7

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xwd.1
