#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xwd
Version  : 1.0.6
Release  : 1
URL      : https://www.x.org/releases/individual/app/xwd-1.0.6.tar.gz
Source0  : https://www.x.org/releases/individual/app/xwd-1.0.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xwd-bin
Requires: xwd-doc
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xkbfile)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
xwd - dump an image of an X window
All questions regarding this software should be directed at the
Xorg mailing list:

%package bin
Summary: bin components for the xwd package.
Group: Binaries

%description bin
bin components for the xwd package.


%package doc
Summary: doc components for the xwd package.
Group: Documentation

%description doc
doc components for the xwd package.


%prep
%setup -q -n xwd-1.0.6

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xwd

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
