#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xwd
Version  : 1.0.9
Release  : 9
URL      : https://www.x.org/releases/individual/app/xwd-1.0.9.tar.gz
Source0  : https://www.x.org/releases/individual/app/xwd-1.0.9.tar.gz
Source1  : https://www.x.org/releases/individual/app/xwd-1.0.9.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xwd-bin = %{version}-%{release}
Requires: xwd-license = %{version}-%{release}
Requires: xwd-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xkbfile)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
xwd - dump an image of an X window
----------------------------------
All questions regarding this software should be directed at the
Xorg mailing list:

%package bin
Summary: bin components for the xwd package.
Group: Binaries
Requires: xwd-license = %{version}-%{release}

%description bin
bin components for the xwd package.


%package license
Summary: license components for the xwd package.
Group: Default

%description license
license components for the xwd package.


%package man
Summary: man components for the xwd package.
Group: Default

%description man
man components for the xwd package.


%prep
%setup -q -n xwd-1.0.9
cd %{_builddir}/xwd-1.0.9
pushd ..
cp -a xwd-1.0.9 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1685984558
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1685984558
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xwd
cp %{_builddir}/xwd-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xwd/6b0e3fce4ba4e2a4fba4301ed4e356885de100f7 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/xwd
/usr/bin/xwd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xwd/6b0e3fce4ba4e2a4fba4301ed4e356885de100f7

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xwd.1
